steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/$_REPO_OWNERurzedo/$$_SECRET_TESTE'
      - '.'
    secretEnv: ['_SECRET_TESTE']

  - id: Push
    name: gcr.io/cloud-builders/docker
    args: [$_PUSH, 'gcr.io/$PROJECT_ID/github.com/lucasurzedo/$$_SECRET_TESTE']
    secretEnv: ['_SECRET_TESTE']

  - id: get-secrets-teste
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: [ '-c', "gcloud secrets versions access latest --secret=secret-test > teste.txt" ]

options:
  substitutionOption: ALLOW_LOOSE

images:
  - 'gcr.io/$PROJECT_ID/github.com/lucasurzedo/anyjs-observer:latest'

substitutions:
  _REPO_OWNER: lucas
  _PUSH: push
  
availableSecrets:
  secretManager:
  - versionName: projects/1061558947426/secrets/secret-test/versions/latest
    env: '_SECRET_TESTE'