steps:
  - id: get-secrets-teste
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: [ '-c', "gcloud secrets versions access latest --secret=secret-test > teste.json" ]

  - id: create-secret-test
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: ['-c', "gcloud secrets create `grep -oP '(?<=\"key\": \")[^\"]*' teste.json` --data-file=teste.json"]
