steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/lucasurzedo/anyjs-observer:latest'
      - '.'
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/github.com/lucasurzedo/anyjs-observer:latest'
    id: Push

options:
  substitutionOption: ALLOW_LOOSE

images:
  - 'gcr.io/$PROJECT_ID/github.com/lucasurzedo/anyjs-observer:latest'