steps:
  # - id: Build
  #   name: gcr.io/cloud-builders/docker
  #   args:
  #     - build
  #     - '--no-cache'
  #     - '-t'
  #     - 'gcr.io/$PROJECT_ID/github.com/$_REPO_OWNERurzedo/anyjs-observer:latest'
  #     - '.'

  # - id: Push
  #   name: gcr.io/cloud-builders/docker
  #   args: [$_PUSH, 'gcr.io/$PROJECT_ID/github.com/lucasurzedo/anyjs-observer:latest']

  - id: get-secrets-teste
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: [ '-c', "gcloud secrets versions access latest --secret=secret-test > teste.txt" ]

  - id: create-secret-test
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args: ['-c', "gcloud secrets create $$_SECRET_TESTE --data-file=teste.txt]

# options:
#   substitutionOption: ALLOW_LOOSE

# images:
#   - 'gcr.io/$PROJECT_ID/github.com/lucasurzedo/anyjs-observer:latest'

substitutions:
  _REPO_OWNER: lucas
  _PUSH: push
  
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/secret-test/versions/latest
    env: '_SECRET_TESTE'